version: '3'

services:
  server:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - API

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123pass
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 123pass
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - API

networks:
  API:
